Lab #8
natasha1237/Labs pull request #2
Opened 2018-12-27 20:22 UTC by natasha1237

2018-12-27 20:23 UTC, natasha1237 commented
@nechaido review please , IP-81 , Goryanina Natasha

2018-12-27 20:32 UTC, nechaido commented
Задание?

2018-12-27 20:41 UTC, natasha1237 commented
@nechaido  Задані три цілочисельні матриці розмірності m x m, що містять від'ємні елементи. З’ясувати, яка з цих матриць має найменшу суму модулів діагональних елементів тих рядків, що починаються з від'ємного елемента. Упорядкувати рядки визначеної матриці за збільшенням значень її елементів.

2018-12-27 21:14 UTC, nechaido requested changes
Оформление.

2018-12-27 22:24 UTC, natasha1237 commented
@nechaido а що не так?

2018-12-27 22:58 UTC, natasha1237 commented
@nechaido виправила)

2018-12-28 19:43 UTC, nechaido approved these changes
Принято.

2019-01-29 10:51 UTC, closed without merging